version: 2.1

setup: true

orbs:
  continuation: circleci/continuation@0.1.2

executors:
  kydeps-executor:
    docker:
      - image: kyotov/kydeps:latest
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD

jobs:          
  generate-build-universe:
    executor: kydeps-executor
    working_directory: "~/src"
    steps:
      - checkout
      - run: cd ~/src && git submodule update --init --recursive
      - run: cmake -S ~/src/mode-2/kydeps -D KYDEPS_CI_UNIVERSE_CONFIGURE=ON
      - continuation/continue:
          configuration_path: universe.yml


workflows:
  setup:
    jobs:
      - generate-build-universe
